<a href="https://colab.research.google.com/github/AzadMehedi/Data-Pipeline/blob/main/Implementing_Machine_Learninng_Pipelines_Using_Sklearn_And_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# import packages

In [2]:
from sklearn.pipeline import Pipeline

# for feeature scaling
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [7]:
# steps to follow

steps = [('standard_scaler',StandardScaler()),
         ('logistic_regression',LogisticRegression())]

steps

[('standard_scaler', StandardScaler()),
 ('logistic_regression', LogisticRegression())]

In [9]:
# creating Pipeline

pipe = Pipeline(steps)
pipe

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('logistic_regression', LogisticRegression())])

In [10]:
# another way to visualize the pipeline
from sklearn import set_config
set_config(display='diagram')
pipe

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('logistic_regression', LogisticRegression())])

In [11]:
# crate a dataset
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=1000)


In [12]:
# checking the shape of X_train value
X.shape

(1000, 20)

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [14]:
# lets check our X_train values
X_train

array([[ 0.11607255, -0.78594267,  0.96866284, ...,  0.56977795,
         0.77477936,  1.13974489],
       [-1.75293727, -2.18569444, -0.36742298, ..., -0.40523773,
         0.07434566, -0.72881531],
       [ 2.53958007,  2.23422847,  0.70410703, ..., -3.26962367,
        -0.37285768, -0.73655571],
       ...,
       [ 0.10828513,  0.68462408,  0.02677359, ...,  0.51052497,
         0.23922756,  1.46172049],
       [-1.27583315,  0.73772473,  0.30995542, ..., -1.14411728,
         0.44301917, -1.26951001],
       [-0.87600339,  0.9283777 ,  2.17794264, ..., -1.30040397,
        -0.93686656, -1.60553605]])

In [15]:
# fit the tain values into our pipeline (Statndar scaler and logistic regression)
pipe.fit(X_train, y_train)

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('logistic_regression', LogisticRegression())])

In [16]:
# we can now predict if we want
pipe.predict(X_test)

array([1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0])

# lets complex it a bit more
# Example 2
## combine multiple preprocessing steps, classifiers
- Displaying a pipeline with 
1. Standard Scaler 
2. Dimentionality Reduction
3. then estimator

In [32]:
# import packages

from sklearn.decomposition import PCA
from sklearn.svm import SVC


import warnings
warnings.filterwarnings('ignore')

In [36]:
steps = [('scaling',StandardScaler()),
         ('pca',PCA(n_components=3)),
         ('svc',SVC())]


In [38]:
pipe2 = Pipeline(steps)
pipe2

Pipeline(steps=[('scaling', StandardScaler()), ('pca', PCA(n_components=3)),
                ('svc', SVC())])

In [39]:
pipe2.fit(X_train, y_train)

Pipeline(steps=[('scaling', StandardScaler()), ('pca', PCA(n_components=3)),
                ('svc', SVC())])

In [41]:
pipe2.predict(X_test)

array([1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0])

# Example 3
## complex example of column transformer

In [46]:
from sklearn.impute import SimpleImputer   # to handle missing values. this is specificly used for numerical variable.
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [45]:
# for numerical processing pipeline
numeric_processor = Pipeline(
    steps = [('imputation_mean',SimpleImputer(missing_values=np.nan, strategy='mean')),
            ('scaler',StandardScaler())]
 )
numeric_processor

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [57]:
# for categorical processing pipeline

categorical_processor = Pipeline(
    steps = [('imputation_constant',SimpleImputer(fill_value='missing', strategy='contant')),
             ('onehot',OneHotEncoder(handle_unknown='ignore'))]
)
categorical_processor

Pipeline(steps=[('imputation_constant',
                 SimpleImputer(fill_value='missing', strategy='contant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [51]:
# combine both the pipeline
# combine processing technique

from sklearn.compose import ColumnTransformer

In [61]:
preprocessor = ColumnTransformer(
    [('categorical',categorical_processor,['Gender','City']),     # demo column
     ('numerical',numeric_processor,['Age','Height'])]            # demo column
)
preprocessor

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_constant',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='contant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['Gender', 'City']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['Age', 'Height'])])

In [62]:
# add an estimator
# creating a custom pipeline

from sklearn.pipeline import make_pipeline

In [63]:
/# combine the entire thing along with the simple estimator and apply Logistic Registic regression algorithm.

make_pipeline(preprocessor, LogisticRegression)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_constant',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='contant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Gender', 'City']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Age', 'Height'])])),
                ('type',
                 <class 'sklearn.linear_model._logistic.LogisticRegression'>)])